### ISSUE TITLE
Parent container not taking height

### ISSUE THREAD

**Issue by manimuthukumar6** [rexxars/react-layout-pack#9]
Hi ,

Because of position absolute parent relative container not taking the height of the child contents.

Ex:

Ul has list of child elements with position absolute value but it's not taking the height of the child components.

Is there any props to calculate and set the height to the parent container ? Because of this container height issue not able place any footer component.

![image](https://cloud.githubusercontent.com/assets/417217/18025838/696e56d4-6c53-11e6-8ebd-d11a802126fa.png)

**Comment by mediabakery** [comment]
Fixed with #8

**Comment by manimuthukumar6** [comment]
Added setHeight=true ; But Now i am facing " Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined ". I hope already this issue fixed. Could you please confirm the latest version (0.2.2) have this fix?

If you update the demo site as well it would be better. Still, I am not able to see the height of the container after reposition.

Demo Link:

http://rexxars.github.io/react-layout-pack/

![image](https://cloud.githubusercontent.com/assets/417217/22021879/87363896-dce5-11e6-84f0-86ecfe72198a.png)

**Comment by rexxars** [comment]
Sorry about that @manimuthukumar6  - the latest release (0.2.3) should fix this. Also updated the demo.

**Comment by manimuthukumar6** [comment]
Hi Rexxars,

Thanks a lot for your quick fix. 

Cheers !!!
